module: SAPCAI
author: SAP SE
author_url: https://www.sap.com
theme: jony
exclude: Sources/SAPCAI/Foundation/Utility/SAPIcons.swift
hide_documentation_coverage: true
github_url: https://github.com/SAP/cloud-sdk-ios-cai
