name: Jazzy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      module_version:
        description: 'Module Version'
        required: true
        default: 'Latest'
      deploy:
        description: 'Deploy'
        required: true
        default: 'false'

jobs:
  Jazzy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          brew install sourcekitten
          gem install jazzy
      - name: Get tag name from release
        if: github.event_name == 'release'
        uses: actions/github-script@v4
        id: release-version
        with:
          script: return context.payload.release.tag_name
          result-encoding: string
      - name: Set MVERSION (Release)
        if: github.event_name == 'release'
        run: |
          echo "MVERSION=${{ steps.release-version.outputs.result }}" >> $GITHUB_ENV
      - name: Set MVERSION (Manual Dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "MVERSION=${{ github.event.inputs.module_version }}" >> $GITHUB_ENV
      - name: Generate Documentation (Jazzy)
        run: make jazzy VERSION="${{ env.MVERSION }}"
      - name: Push to gh-pages
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' &&  github.event.inputs.deploy == 'true'
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" out
          cd out
          git checkout gh-pages
          git rm -rf .
          cd ..
          cp -a docs/. out/.
          cd out
          git add -A
          git commit -m "Automated deployment to GitHub Pages: ${GITHUB_SHA}" --allow-empty
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload documentation as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: docs
