name: PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  conventionalcommit-verification:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
            configFile: '.github/configActions/commitlint.config.js'

  ReuseComplianceCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1

  CodeFormattingCheck:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Mint packages
        id: mint-cache
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - name: Install Mint
        run: |
          brew upgrade mint || brew install mint || true
      - name: Install swiftformat via mint
        if: steps.mint-cache.outputs.cache-hit != 'true'
        run: mint bootstrap
      - name: Format Swift code
        run: mint run swiftformat --verbose .
      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD

  WipCheck:
    name: Prevent WIP PRs from being merged
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
